Fix: invalid handling of OONI Run v1 link with partial URL
ooni/probe-ios pull request #528
Opened 2023-07-28 07:41 UTC by aanorbel

Fixes  https://github.com/ooni/probe/issues/2515

## Proposed Changes

  - Modified `OoniRunViewController#validateLink` to use updated code that allows a better validation.

![Simulator Screenshot - iPhone 14 Pro - 2023-07-28 at 08 40 57](https://github.com/ooni/probe-ios/assets/17911892/37e81a21-b416-4911-a775-826797ef93c6)

2023-07-28 11:26 UTC, bassosimone requested changes
Please, write tests covering each of the possible error conditions. You can use https://www.onlinegdb.com/V81JCf11o to get some inspiration about possible test cases.

2023-07-28 11:26 UTC, bassosimone commented on ooniprobe/View/OONIRun/OoniRunViewController.m
> +    }
```suggestion
```

We don't need this part.

2023-07-31 09:28 UTC, hellais commented on ooniprobe/View/OONIRun/OoniRunViewController.m
> +    if (urlString.length > 2083) {
I would suggest removing this constraint on the maximum URL length. AFAIK this is a limitation that only used to exist in older internet explorer versions, but it's not really something part of the specification for URLs.

2023-07-31 09:28 UTC, hellais reviewed
Suggested a small fix, but otherwise LGTM 🐳

2023-07-31 11:26 UTC, hellais commented
Lgtm

2023-07-31 11:44 UTC, merged